import type { Metadata } from "next";
import { Georama, Roboto_Mono } from "next/font/google"; // Cambio a fuentes reales
import "./globals.css";
import Header from "./components/header";
import React from "react";
import Footer from "./components/FooterMovil"; // Importa el Footer

// Configuración de las fuentes
const georamaSans = Georama({
  variable: "--font-georama-sans",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

// Metadatos de la página
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${georamaSans.variable} ${robotoMono.variable} antialiased layout-container`}
      >
        <Header />
        <main className="content-container">{children}</main>
        <div className="block sm:hidden footer-container">
          <Footer />
        </div>
      </body>
    </html>
  );
}
